trigger: none

resources:
- repo: self

parameters:
  - name: variableGroup
    displayName: 'Select the Dependency You Want to Build'
    type: string
    default: 'goonly'
    values:
      - 'gosql'
      - 'nodeonly'
      - 'phponly'
      - 'phpsql'

variables:
  - group: ${{ parameters.variableGroup }}

pool:
    name: FloTechnology-Azure-Test

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    steps:
      - script: |
          echo "Copy the folder where scripts placed..."
          cp agent_installation.sh $(rootfilePath)
          cp extension_script.sh $(rootfilePath)
          ls -l $(rootfilePath)
        displayName: 'Copy file from parent directory to $(rootfilePath)'
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          containerRegistry: '$(dockerRegistryServiceConnection)'
          repository: '$(imageRepository)'
          command: 'buildAndPush'
          Dockerfile: '$(dockerfilePath)'
          tags: '$(tag)'

      - task: replacetokens@6
        inputs:
          root: '$(rootfilePath)'
          sources: 'deployment.yml'
          tokenPattern: 'azpipelines'

      - task: Kubernetes@1
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: '$(kubernetesConnection)'
          command: 'apply'
          useConfigurationFile: true
          configuration: '$(deploymentfilePath)'
