apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-agent
spec:
  replicas: 2
  progressDeadlineSeconds: 1800
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
        - name: azdevops-agent
          image: <containerregistryurl>/kubeagent:$(Build.BuildId)
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: "1"
              memory: "1G"
            limits:
              cpu: "2"
              memory: "2G"
          env:
            - name: AZP_POOL
              value: <agent pool name>
            - name: AZP_URL
              value: <devops organization url>
            - name: AZP_PAT
              value: <pat for create agent>
          volumeMounts:
          - name: docker-graph-storage
            mountPath: /var/run/docker.sock   
      volumes:
      - name: docker-graph-storage
        hostPath:
            path: /var/run/docker.sock
