{{- if .Values.github.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "azure-devops-agent.githubSecretName" . }}
  labels:
    {{- include "azure-devops-agent.labels" . | nindent 4 }}
data:
  personalAccessToken: {{ .Values.github.pat | b64enc | quote }}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "azure-devops-agent.githubTriggerAuthName" . }}
  labels:
    {{- include "azure-devops-agent.labels" . | nindent 4 }}
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: {{ include "azure-devops-agent.githubSecretName" . }}
      key: personalAccessToken
{{- end }}
