apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: azure-devops-auth
  namespace: azure-agents
  labels:
    app.kubernetes.io/part-of: azure-devops-agents
data:
  # echo -n "your-pat-here" | base64
  personalAccessToken: "<BASE64_ENCODED_PAT>"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-devops-trigger-auth
  namespace: azure-agents
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: azure-devops-auth
      key: personalAccessToken
